@echo off
echo Starting Django server...
cd /d c:\Users\HP\OneDrive\Desktop\Github_Projects\airline_ticket_booking
echo Activating virtual environment...
call env\Scripts\activate
echo Changing to airline directory...
cd airline
echo Starting Django server on port 8000...
python manage.py runserver
pause