# Generated by Django 6.0 on 2026-01-01 12:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('origin', models.CharField(db_index=True, max_length=100)),
                ('destination', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('aircraft_type', models.CharField(default='Boeing 737', max_length=50)),
                ('total_seats', models.PositiveIntegerField(default=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flights', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'airline_flights',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], default='ECONOMY', max_length=20)),
                ('row_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('seat_letter', models.CharField(max_length=1)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seats', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.flight')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'airline_seats',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(blank=True, max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('INITIATED', 'Initiated'), ('SEAT_HELD', 'Seat Held'), ('PAYMENT_PENDING', 'Payment Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=20)),
                ('seat_hold_until', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('refund_processed', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.seat')),
            ],
            options={
                'db_table': 'airline_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time', 'origin', 'destination'], name='airline_fli_departu_a218af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['is_active', 'departure_time'], name='airline_fli_is_acti_78b0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['flight', 'is_booked'], name='airline_sea_flight__f1b5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['seat_class', 'is_booked'], name='airline_sea_seat_cl_941983_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['state', 'created_at'], name='airline_boo_state_d9665a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['seat_hold_until'], name='airline_boo_seat_ho_2096fa_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passenger_email'], name='airline_boo_passeng_f7d7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='airline_boo_booking_ef9424_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['travel_date'], name='airline_boo_travel__4295ab_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['cancelled_date'], name='airline_boo_cancell_b2b067_idx'),
        ),
    ]
