# Generated by Django 6.0 on 2026-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_optimize_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('airline_code', models.CharField(choices=[('AI', 'Air India'), ('SG', 'SpiceJet'), ('6E', 'IndiGo'), ('UK', 'Vistara'), ('G8', 'GoAir'), ('I5', 'AirAsia India'), ('9W', 'Jet Airways'), ('DN', 'Alliance Air'), ('S2', 'JetLite'), ('IT', 'Kingfisher')], db_index=True, max_length=2)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitoring_users',
                'ordering': ['airline_code', 'username'],
                'indexes': [models.Index(fields=['username', 'is_active'], name='monitoring__usernam_cbc6fd_idx'), models.Index(fields=['airline_code', 'is_active'], name='monitoring__airline_223e0d_idx')],
            },
        ),
    ]
