# Generated by Django 6.0 on 2026-01-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_monitoringuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringuser',
            options={'ordering': ['username']},
        ),
        migrations.RemoveIndex(
            model_name='monitoringuser',
            name='monitoring__usernam_cbc6fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='monitoringuser',
            name='monitoring__airline_223e0d_idx',
        ),
        migrations.RemoveField(
            model_name='monitoringuser',
            name='airline_code',
        ),
        migrations.RemoveField(
            model_name='monitoringuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='monitoringuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='monitoringuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='monitoringuser',
            name='updated_date',
        ),
    ]
