# Generated by Django 6.0 on 2026-01-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_adminuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['airline_code', 'username']},
        ),
        migrations.AddField(
            model_name='adminuser',
            name='airline_code',
            field=models.CharField(blank=True, choices=[('AI', 'Air India'), ('SG', 'SpiceJet'), ('6E', 'IndiGo'), ('UK', 'Vistara'), ('G8', 'GoAir'), ('I5', 'AirAsia India'), ('9W', 'Jet Airways'), ('DN', 'Alliance Air'), ('S2', 'JetLite'), ('IT', 'Kingfisher')], db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
