# Generated by Django 6.0 on 2026-01-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_adminuser_options_adminuser_airline_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['airline_code', 'admin_name']},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='admin_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='airline_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='airline_code',
            field=models.CharField(choices=[('AI', 'Air India'), ('SG', 'SpiceJet'), ('6E', 'IndiGo'), ('UK', 'Vistara'), ('G8', 'GoAir'), ('I5', 'AirAsia India'), ('9W', 'Jet Airways'), ('DN', 'Alliance Air'), ('S2', 'JetLite'), ('IT', 'Kingfisher')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(default='admin@airline.com', max_length=254),
        ),
    ]
