# Generated by Django 6.0 on 2026-01-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_adminuser_options_remove_adminuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(default='+91-9876543210', max_length=15),
        ),
    ]
