# Generated by Django 6.0 on 2026-01-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_adminuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_code',
            field=models.CharField(db_index=True, default='AI', max_length=2),
        ),
    ]
