# Generated by Django 6.0 on 2026-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_flight_airline_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='actual_password',
            field=models.CharField(default='admin123', max_length=50),
        ),
    ]
