# Generated by Django 6.0 on 2026-01-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_adminuser_actual_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringuser',
            name='actual_password',
            field=models.CharField(default='admin123', max_length=50),
        ),
    ]
